version: '3.8'
services:
  front:
    build: 
      context: .
      target: client
    ports:
      - 8081:8080
    command: npm run serve
  back:
    build:
      context: .
      target: server
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - maven-repo:/root/.m2
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=arosaje
    ports:
      - 3306:3306

volumes:
  maven-repo: